### ISSUE TITLE
Breaks on mutually recursive types

### ISSUE THREAD

**Issue by shonfeder** [erebuxy/ppx_make#12]
More or less the same problem (or perhaps just a limitation?) reported at https://github.com/ocaml-ppx/ppx_deriving/issues/272 affects this library.

```ocaml
module Ex = struct
  type t = {a : int; b: s}
  [@@deriving make]

  and s = int
end
```

Fails with

```
File "ex.ml", line 5, characters 6-7:
5 |   and s = int
          ^
Error: core type s cannot be derived
```

**Comment by shonfeder** [comment]
Thanks for the quick fix!

**Comment by bn-d** [comment]
Thanks for the feedback! Release PR at ~~https://github.com/ocaml/opam-repository/pull/25092~~ https://github.com/ocaml/opam-repository/pull/25093
